import type {
  Category,
  Level,
  Locale,
  LocalizedText,
  Topic,
} from "../domain/types";

type Triple = [EN: string, PL: string, JA: string];

interface TopicSeed {
  id: string;
  level: Level;
  languages: Topic["languages"];
  category: Category;
  artIndex: number;
  atlas: 1 | 2;
  title: Triple;
  description: Triple;
  mainPrompt: Triple;
  followUps: Record<Locale, string[]>;
  vocabulary: Array<
    [EN: string, PL: string, JA: string, partOfSpeech: string]
  >;
}

const localized = ([EN, PL, JA]: Triple): LocalizedText => ({ EN, PL, JA });

const createTopic = (seed: TopicSeed): Topic => ({
  id: seed.id,
  level: seed.level,
  languages: seed.languages,
  category: seed.category,
  artIndex: seed.artIndex,
  atlas: seed.atlas,
  title: localized(seed.title),
  description: localized(seed.description),
  mainPrompt: localized(seed.mainPrompt),
  followUps: seed.followUps,
  vocabulary: {
    EN: seed.vocabulary.map(([word, translation, , part]) => ({
      word,
      translation,
      part,
    })),
    PL: seed.vocabulary.map(([word, translation, , part]) => ({
      word: translation,
      translation: word,
      part,
    })),
    JA: seed.vocabulary.map(([word, , translation, part]) => ({
      word: translation,
      translation: word,
      part,
    })),
  },
});

const topicSeeds: TopicSeed[] = [
  {
    id: "my-neighborhood",
    level: "A1",
    languages: ["EN", "PL"],
    category: "Daily Life",
    artIndex: 1,
    atlas: 1,
    title: ["My Neighborhood", "Moja okolica", "私の近所"],
    description: [
      "Describe the places and people near your home.",
      "Opisz miejsca i ludzi w pobliżu swojego domu.",
      "家の近くにある場所や、近所の人について話しましょう。",
    ],
    mainPrompt: [
      "What do you like about your neighborhood?",
      "Co lubisz w swojej okolicy?",
      "自分の近所のどんなところが好きですか？",
    ],
    followUps: {
      EN: [
        "Is your neighborhood quiet or busy?",
        "Where do you usually go for a walk?",
        "Is there a shop or café near your home?",
        "Who do you often meet in your neighborhood?",
        "What place would you like to add nearby?",
        "How is your neighborhood different at night?",
      ],
      PL: [
        "Czy Twoja okolica jest spokojna czy ruchliwa?",
        "Gdzie zwykle chodzisz na spacer?",
        "Czy blisko Twojego domu jest sklep lub kawiarnia?",
        "Kogo często spotykasz w swojej okolicy?",
        "Jakiego miejsca brakuje w pobliżu?",
        "Jak Twoja okolica zmienia się wieczorem?",
      ],
      JA: [
        "近所は静かですか、それともにぎやかですか？",
        "いつもどこを散歩しますか？",
        "家の近くに店やカフェがありますか？",
        "近所でよく誰に会いますか？",
        "近くにどんな場所があったらいいですか？",
        "夜になると近所はどう変わりますか？",
      ],
    },
    vocabulary: [
      ["neighborhood", "okolica", "近所", "noun"],
      ["nearby", "w pobliżu", "近くに", "adverb"],
      ["quiet", "spokojny", "静かな", "adjective"],
      ["busy", "ruchliwy", "にぎやかな", "adjective"],
      ["go for a walk", "iść na spacer", "散歩に行く", "verb"],
    ],
  },
  {
    id: "workplace-communication",
    level: "B1",
    languages: ["EN", "PL"],
    category: "Work & Career",
    artIndex: 0,
    atlas: 1,
    title: [
      "Communication at Work",
      "Komunikacja w pracy",
      "職場のコミュニケーション",
    ],
    description: [
      "Explore habits that help colleagues understand one another.",
      "Poznaj nawyki, które pomagają współpracownikom się rozumieć.",
      "同僚がお互いを理解するために役立つ習慣を考えましょう。",
    ],
    mainPrompt: [
      "What makes communication at work clear and respectful?",
      "Co sprawia, że komunikacja w pracy jest jasna i pełna szacunku?",
      "職場で分かりやすく丁寧に伝えるには、何が大切ですか？",
    ],
    followUps: {
      EN: [
        "When is a meeting better than a message?",
        "How do you ask a colleague for help?",
        "What causes misunderstandings at work?",
        "How should people share bad news?",
        "Is direct communication always better?",
        "Which communication habit would you improve?",
      ],
      PL: [
        "Kiedy spotkanie jest lepsze niż wiadomość?",
        "Jak prosisz współpracownika o pomoc?",
        "Co powoduje nieporozumienia w pracy?",
        "Jak należy przekazywać złe wiadomości?",
        "Czy bezpośrednia komunikacja jest zawsze lepsza?",
        "Który nawyk komunikacyjny chcesz poprawić?",
      ],
      JA: [
        "メッセージより会議の方がよいのはどんな時ですか？",
        "同僚にどうやって助けを求めますか？",
        "職場で誤解が生まれる原因は何ですか？",
        "悪い知らせはどう伝えるべきですか？",
        "率直な伝え方はいつもよいですか？",
        "どんなコミュニケーション習慣を改善したいですか？",
      ],
    },
    vocabulary: [
      ["colleague", "współpracownik", "同僚", "noun"],
      ["misunderstanding", "nieporozumienie", "誤解", "noun"],
      ["respectful", "pełen szacunku", "丁寧な", "adjective"],
      ["clarify", "wyjaśnić", "明確にする", "verb"],
      ["share feedback", "przekazać opinię", "意見を伝える", "verb"],
    ],
  },
  {
    id: "digital-wellbeing",
    level: "B2",
    languages: ["EN", "PL"],
    category: "Health & Wellness",
    artIndex: 4,
    atlas: 1,
    title: ["Digital Wellbeing", "Cyfrowy dobrostan", "デジタル・ウェルビーイング"],
    description: [
      "Discuss how technology can support life without taking it over.",
      "Porozmawiaj o tym, jak technologia może wspierać życie, nie przejmując nad nim kontroli.",
      "テクノロジーに振り回されず、生活に生かす方法を話しましょう。",
    ],
    mainPrompt: [
      "How can people build a healthier relationship with technology?",
      "Jak ludzie mogą zbudować zdrowszą relację z technologią?",
      "テクノロジーとより健全に付き合うにはどうすればよいですか？",
    ],
    followUps: {
      EN: [
        "Which notifications are genuinely useful?",
        "How does screen time affect your concentration?",
        "Should phones be kept out of bedrooms?",
        "What makes an app difficult to stop using?",
        "Can technology help people rest?",
        "Which digital boundary works well for you?",
      ],
      PL: [
        "Które powiadomienia są naprawdę przydatne?",
        "Jak czas przed ekranem wpływa na Twoją koncentrację?",
        "Czy telefony powinny być poza sypialnią?",
        "Co sprawia, że trudno przestać korzystać z aplikacji?",
        "Czy technologia może pomagać w odpoczynku?",
        "Jaka cyfrowa granica dobrze Ci służy?",
      ],
      JA: [
        "本当に役立つ通知はどれですか？",
        "画面を見る時間は集中力にどう影響しますか？",
        "寝室にスマートフォンを持ち込まない方がよいですか？",
        "アプリをやめにくくするものは何ですか？",
        "テクノロジーは休息にも役立ちますか？",
        "自分に合っているデジタル上のルールは何ですか？",
      ],
    },
    vocabulary: [
      ["screen time", "czas przed ekranem", "スクリーンタイム", "noun"],
      ["notification", "powiadomienie", "通知", "noun"],
      ["concentration", "koncentracja", "集中力", "noun"],
      ["boundary", "granica", "境界線", "noun"],
      ["switch off", "odłączyć się", "デジタル機器から離れる", "verb"],
    ],
  },
  {
    id: "ethical-tourism",
    level: "C1",
    languages: ["EN", "PL"],
    category: "Travel & Culture",
    artIndex: 3,
    atlas: 1,
    title: ["Ethical Tourism", "Etyczna turystyka", "責任ある観光"],
    description: [
      "Debate how travel can benefit visitors and host communities.",
      "Porozmawiaj o tym, jak podróże mogą służyć turystom i lokalnym społecznościom.",
      "旅行者と受け入れる地域の双方に役立つ観光について議論しましょう。",
    ],
    mainPrompt: [
      "What responsibilities do travelers have toward the places they visit?",
      "Jaką odpowiedzialność mają podróżni wobec odwiedzanych miejsc?",
      "旅行者は訪問先に対してどんな責任を持つべきですか？",
    ],
    followUps: {
      EN: [
        "When does tourism place too much pressure on a city?",
        "How can visitors support local businesses?",
        "Should fragile destinations limit visitor numbers?",
        "Can short-term rentals harm local communities?",
        "How should travelers approach cultural traditions?",
        "Is flying less the most meaningful individual action?",
      ],
      PL: [
        "Kiedy turystyka wywiera zbyt dużą presję na miasto?",
        "Jak turyści mogą wspierać lokalne firmy?",
        "Czy delikatne miejsca powinny ograniczać liczbę odwiedzających?",
        "Czy najem krótkoterminowy szkodzi lokalnym społecznościom?",
        "Jak podróżni powinni podchodzić do lokalnych tradycji?",
        "Czy rzadsze latanie jest najważniejszym działaniem jednostki?",
      ],
      JA: [
        "観光が都市に過度な負担をかけるのはどんな時ですか？",
        "旅行者は地元の店をどう支援できますか？",
        "環境が壊れやすい場所は訪問者数を制限すべきですか？",
        "短期賃貸は地域社会に悪影響を与えますか？",
        "旅行者は地域の伝統にどう向き合うべきですか？",
        "飛行機の利用を減らすことが最も有効な個人行動ですか？",
      ],
    },
    vocabulary: [
      ["host community", "społeczność przyjmująca", "受け入れ地域", "noun"],
      ["overtourism", "nadmierna turystyka", "オーバーツーリズム", "noun"],
      ["local economy", "lokalna gospodarka", "地域経済", "noun"],
      ["cultural heritage", "dziedzictwo kulturowe", "文化遺産", "noun"],
      ["minimize impact", "ograniczać wpływ", "影響を最小限にする", "verb"],
    ],
  },
  {
    id: "at-the-cafe",
    level: "A1",
    languages: ["EN", "JA"],
    category: "Daily Life",
    artIndex: 1,
    atlas: 1,
    title: ["At the Café", "W kawiarni", "カフェで"],
    description: [
      "Practise ordering, asking simple questions, and talking about tastes.",
      "Ćwicz zamawianie, proste pytania i rozmowę o smakach.",
      "注文や簡単な質問、好きな味について話す練習をしましょう。",
    ],
    mainPrompt: [
      "What do you usually order at a café?",
      "Co zwykle zamawiasz w kawiarni?",
      "カフェでいつも何を注文しますか？",
    ],
    followUps: {
      EN: [
        "Do you prefer coffee, tea, or juice?",
        "Would you like something sweet?",
        "Do you visit cafés alone or with friends?",
        "What makes a café comfortable?",
        "How often do you try a new drink?",
        "What would you recommend to a visitor?",
      ],
      PL: [
        "Wolisz kawę, herbatę czy sok?",
        "Czy masz ochotę na coś słodkiego?",
        "Chodzisz do kawiarni sam czy z przyjaciółmi?",
        "Co sprawia, że kawiarnia jest przytulna?",
        "Jak często próbujesz nowego napoju?",
        "Co poleciłbyś odwiedzającej osobie?",
      ],
      JA: [
        "コーヒー、紅茶、ジュースのどれが好きですか？",
        "甘いものはいかがですか？",
        "一人でカフェに行きますか、友達と行きますか？",
        "居心地のよいカフェには何がありますか？",
        "どのくらいの頻度で新しい飲み物を試しますか？",
        "旅行者に何をおすすめしますか？",
      ],
    },
    vocabulary: [
      ["menu", "menu", "メニュー", "noun"],
      ["order", "zamówienie", "注文", "noun"],
      ["sweet", "słodki", "甘い", "adjective"],
      ["comfortable", "przytulny", "居心地のよい", "adjective"],
      ["I would like", "poproszę", "〜をお願いします", "phrase"],
    ],
  },
  {
    id: "learning-through-games",
    level: "A2",
    languages: ["EN", "JA"],
    category: "Education",
    artIndex: 4,
    atlas: 2,
    title: ["Learning Through Games", "Nauka przez gry", "ゲームで学ぶ"],
    description: [
      "Share how games can make practice active and memorable.",
      "Opowiedz, jak gry mogą sprawić, że nauka jest aktywna i łatwa do zapamiętania.",
      "ゲームが学習を活発で記憶に残るものにする方法を話しましょう。",
    ],
    mainPrompt: [
      "What can people learn through games?",
      "Czego ludzie mogą nauczyć się dzięki grom?",
      "ゲームを通して何を学べますか？",
    ],
    followUps: {
      EN: [
        "Which game taught you something useful?",
        "Do you prefer playing alone or in a team?",
        "Can losing help people learn?",
        "What makes a learning game fun?",
        "Should schools use more games?",
        "How would you design a language game?",
      ],
      PL: [
        "Która gra nauczyła Cię czegoś przydatnego?",
        "Wolisz grać sam czy w zespole?",
        "Czy przegrywanie pomaga się uczyć?",
        "Co sprawia, że gra edukacyjna jest ciekawa?",
        "Czy szkoły powinny częściej używać gier?",
        "Jak zaprojektowałbyś grę językową?",
      ],
      JA: [
        "役に立つことを教えてくれたゲームは何ですか？",
        "一人で遊ぶのとチームで遊ぶのはどちらが好きですか？",
        "負けることから学べますか？",
        "学習ゲームを楽しくするものは何ですか？",
        "学校でもっとゲームを使うべきですか？",
        "どんな語学ゲームを作りたいですか？",
      ],
    },
    vocabulary: [
      ["rule", "zasada", "ルール", "noun"],
      ["team", "zespół", "チーム", "noun"],
      ["challenge", "wyzwanie", "挑戦", "noun"],
      ["score", "wynik", "得点", "noun"],
      ["learn from mistakes", "uczyć się na błędach", "失敗から学ぶ", "verb"],
    ],
  },
  {
    id: "giving-feedback",
    level: "B2",
    languages: ["EN", "JA"],
    category: "Work & Career",
    artIndex: 9,
    atlas: 2,
    title: ["Giving Useful Feedback", "Dobra informacja zwrotna", "役立つフィードバック"],
    description: [
      "Explore how honest feedback can support growth without discouraging people.",
      "Zastanów się, jak szczera informacja zwrotna może wspierać rozwój bez zniechęcania.",
      "相手を落ち込ませず、成長を支える率直なフィードバックを考えましょう。",
    ],
    mainPrompt: [
      "What makes feedback useful rather than hurtful?",
      "Co sprawia, że informacja zwrotna pomaga, zamiast ranić?",
      "人を傷つけず、役に立つフィードバックとはどんなものですか？",
    ],
    followUps: {
      EN: [
        "Is positive feedback specific enough at most workplaces?",
        "When is the best time to discuss a mistake?",
        "How should a person respond to unfair criticism?",
        "Does written feedback feel different from spoken feedback?",
        "Should managers ask permission before giving advice?",
        "What feedback helped you improve?",
      ],
      PL: [
        "Czy pozytywne opinie w pracy są wystarczająco konkretne?",
        "Kiedy najlepiej omówić błąd?",
        "Jak reagować na niesprawiedliwą krytykę?",
        "Czy pisemna opinia jest odbierana inaczej niż ustna?",
        "Czy przełożony powinien zapytać przed udzieleniem rady?",
        "Jaka informacja zwrotna pomogła Ci się rozwinąć?",
      ],
      JA: [
        "職場の肯定的な評価は十分に具体的ですか？",
        "失敗について話すのに最適なタイミングはいつですか？",
        "不公平な批判にはどう対応すべきですか？",
        "書面と口頭のフィードバックでは感じ方が違いますか？",
        "上司は助言する前に許可を求めるべきですか？",
        "自分の成長に役立ったフィードバックは何ですか？",
      ],
    },
    vocabulary: [
      ["feedback", "informacja zwrotna", "フィードバック", "noun"],
      ["criticism", "krytyka", "批判", "noun"],
      ["specific", "konkretny", "具体的な", "adjective"],
      ["constructive", "konstruktywny", "建設的な", "adjective"],
      ["point out", "wskazać", "指摘する", "verb"],
    ],
  },
  {
    id: "preserving-local-culture",
    level: "C1",
    languages: ["EN", "JA"],
    category: "Travel & Culture",
    artIndex: 2,
    atlas: 1,
    title: ["Preserving Local Culture", "Ochrona lokalnej kultury", "地域文化を守る"],
    description: [
      "Consider how traditions can remain meaningful as communities change.",
      "Zastanów się, jak tradycje mogą zachować znaczenie, gdy społeczności się zmieniają.",
      "地域社会が変化する中で、伝統をどう大切に残せるか考えましょう。",
    ],
    mainPrompt: [
      "How can communities preserve culture without freezing it in the past?",
      "Jak społeczności mogą chronić kulturę, nie zatrzymując jej w przeszłości?",
      "文化を過去のまま固定せずに守るには、どうすればよいですか？",
    ],
    followUps: {
      EN: [
        "Who should decide which traditions receive support?",
        "How can young people reshape local traditions?",
        "Does tourism help preserve culture or commercialize it?",
        "What is lost when a regional language disappears?",
        "Can digital archives keep traditions alive?",
        "When does cultural borrowing become disrespectful?",
      ],
      PL: [
        "Kto powinien decydować, które tradycje otrzymują wsparcie?",
        "Jak młodzi ludzie mogą zmieniać lokalne tradycje?",
        "Czy turystyka chroni kulturę, czy ją komercjalizuje?",
        "Co tracimy, gdy znika język regionalny?",
        "Czy cyfrowe archiwa mogą utrzymać tradycje przy życiu?",
        "Kiedy zapożyczanie kulturowe staje się brakiem szacunku?",
      ],
      JA: [
        "どの伝統を支援するかは誰が決めるべきですか？",
        "若者は地域の伝統をどう変えていけますか？",
        "観光は文化を守りますか、それとも商品化しますか？",
        "地域の言葉が消えると何が失われますか？",
        "デジタル資料で伝統を残せますか？",
        "文化を取り入れることが失礼になるのはどんな時ですか？",
      ],
    },
    vocabulary: [
      ["heritage", "dziedzictwo", "文化遺産", "noun"],
      ["preservation", "ochrona", "保存", "noun"],
      ["regional language", "język regionalny", "地域言語", "noun"],
      ["commercialize", "komercjalizować", "商業化する", "verb"],
      ["pass down", "przekazywać kolejnym pokoleniom", "後世に伝える", "verb"],
    ],
  },
  {
    id: "everyday-kindness",
    level: "A1",
    languages: ["PL", "JA"],
    category: "People & Relationships",
    artIndex: 6,
    atlas: 1,
    title: ["Everyday Kindness", "Codzienna życzliwość", "日常の親切"],
    description: [
      "Talk about small actions that make another person's day better.",
      "Porozmawiaj o małych gestach, które poprawiają komuś dzień.",
      "誰かの一日をよくする小さな親切について話しましょう。",
    ],
    mainPrompt: [
      "What small act of kindness makes you happy?",
      "Jaki mały gest życzliwości sprawia Ci radość?",
      "どんな小さな親切がうれしいですか？",
    ],
    followUps: {
      EN: [
        "When did someone last help you?",
        "How do you thank a person?",
        "Is it easy to ask for help?",
        "How can you help a new student?",
        "Can a smile change someone's day?",
        "What kind thing can you do this week?",
      ],
      PL: [
        "Kiedy ostatnio ktoś Ci pomógł?",
        "Jak dziękujesz drugiej osobie?",
        "Czy łatwo jest prosić o pomoc?",
        "Jak możesz pomóc nowemu uczniowi?",
        "Czy uśmiech może zmienić czyjś dzień?",
        "Co miłego możesz zrobić w tym tygodniu?",
      ],
      JA: [
        "最近、誰かに助けてもらったのはいつですか？",
        "人にどうやって感謝を伝えますか？",
        "助けを求めるのは簡単ですか？",
        "新しい生徒をどう助けられますか？",
        "笑顔で誰かの一日を変えられますか？",
        "今週、どんな親切ができますか？",
      ],
    },
    vocabulary: [
      ["kindness", "życzliwość", "親切", "noun"],
      ["help", "pomoc", "助け", "noun"],
      ["smile", "uśmiech", "笑顔", "noun"],
      ["thankful", "wdzięczny", "感謝している", "adjective"],
      ["offer help", "zaoferować pomoc", "助けを申し出る", "verb"],
    ],
  },
  {
    id: "study-routines",
    level: "A2",
    languages: ["PL", "JA"],
    category: "Education",
    artIndex: 5,
    atlas: 2,
    title: ["Study Routines", "Nawyki w nauce", "勉強の習慣"],
    description: [
      "Compare simple routines for learning regularly and remembering more.",
      "Porównaj proste sposoby na regularną naukę i lepsze zapamiętywanie.",
      "続けて学び、よく覚えるための簡単な習慣を比べましょう。",
    ],
    mainPrompt: [
      "What helps you study regularly?",
      "Co pomaga Ci uczyć się regularnie?",
      "定期的に勉強するために役立つことは何ですか？",
    ],
    followUps: {
      EN: [
        "Where do you concentrate best?",
        "What time of day do you like to study?",
        "Do you make a weekly plan?",
        "How often do you take a break?",
        "What helps you remember new words?",
        "Do you prefer short or long study sessions?",
      ],
      PL: [
        "Gdzie najlepiej się koncentrujesz?",
        "O jakiej porze dnia lubisz się uczyć?",
        "Czy robisz plan na cały tydzień?",
        "Jak często robisz przerwę?",
        "Co pomaga Ci zapamiętywać nowe słowa?",
        "Wolisz krótkie czy długie sesje nauki?",
      ],
      JA: [
        "どこで一番集中できますか？",
        "一日のうち、いつ勉強するのが好きですか？",
        "一週間の計画を立てますか？",
        "どのくらいの頻度で休憩しますか？",
        "新しい単語を覚えるのに何が役立ちますか？",
        "短い勉強と長い勉強のどちらが好きですか？",
      ],
    },
    vocabulary: [
      ["routine", "nawyk", "習慣", "noun"],
      ["break", "przerwa", "休憩", "noun"],
      ["weekly plan", "plan tygodniowy", "週間計画", "noun"],
      ["regularly", "regularnie", "定期的に", "adverb"],
      ["remember", "zapamiętać", "覚える", "verb"],
    ],
  },
  {
    id: "better-public-spaces",
    level: "B1",
    languages: ["PL", "JA"],
    category: "Environment",
    artIndex: 7,
    atlas: 2,
    title: ["Better Public Spaces", "Lepsza przestrzeń publiczna", "よりよい公共空間"],
    description: [
      "Discuss what makes parks, streets, and squares welcoming for everyone.",
      "Porozmawiaj o tym, co sprawia, że parki, ulice i place są przyjazne dla wszystkich.",
      "公園や通り、広場を誰もが使いやすくする方法を話しましょう。",
    ],
    mainPrompt: [
      "What makes a public space pleasant and useful?",
      "Co sprawia, że przestrzeń publiczna jest przyjemna i użyteczna?",
      "快適で役に立つ公共空間には何が必要ですか？",
    ],
    followUps: {
      EN: [
        "Does your area have enough green space?",
        "Who uses the nearest park?",
        "How can public spaces feel safer?",
        "Should streets provide more room for people than cars?",
        "What facilities should be free for everyone?",
        "How would you improve one local place?",
      ],
      PL: [
        "Czy w Twojej okolicy jest wystarczająco dużo zieleni?",
        "Kto korzysta z najbliższego parku?",
        "Jak zwiększyć poczucie bezpieczeństwa w przestrzeni publicznej?",
        "Czy ulice powinny dawać więcej miejsca ludziom niż samochodom?",
        "Które udogodnienia powinny być bezpłatne dla wszystkich?",
        "Jak ulepszyłbyś jedno miejsce w swojej okolicy?",
      ],
      JA: [
        "近所に緑地は十分ありますか？",
        "一番近い公園は誰が利用していますか？",
        "公共空間をより安全にするにはどうすればよいですか？",
        "道路は車より人のための場所を増やすべきですか？",
        "どんな施設を誰でも無料で使えるようにすべきですか？",
        "近所の場所を一つ改善するなら、どうしますか？",
      ],
    },
    vocabulary: [
      ["public space", "przestrzeń publiczna", "公共空間", "noun"],
      ["green space", "teren zielony", "緑地", "noun"],
      ["facility", "udogodnienie", "施設", "noun"],
      ["accessible", "dostępny", "利用しやすい", "adjective"],
      ["improve", "ulepszyć", "改善する", "verb"],
    ],
  },
  {
    id: "aging-societies",
    level: "C1",
    languages: ["PL", "JA"],
    category: "People & Relationships",
    artIndex: 10,
    atlas: 2,
    title: ["Aging Societies", "Starzejące się społeczeństwa", "高齢化社会"],
    description: [
      "Examine how communities can support longer lives across generations.",
      "Zastanów się, jak społeczności mogą wspierać dłuższe życie i relacje między pokoleniami.",
      "長寿と世代間のつながりを社会がどう支えられるか考えましょう。",
    ],
    mainPrompt: [
      "How should societies adapt as people live longer?",
      "Jak społeczeństwa powinny dostosować się do dłuższego życia ludzi?",
      "人々が長生きする時代に、社会はどう変わるべきですか？",
    ],
    followUps: {
      EN: [
        "How can cities support independent living in old age?",
        "Should retirement become more flexible?",
        "What can younger and older generations teach each other?",
        "How might longer lives change education and careers?",
        "Who should carry responsibility for long-term care?",
        "How can society challenge age-related stereotypes?",
      ],
      PL: [
        "Jak miasta mogą wspierać samodzielne życie osób starszych?",
        "Czy przechodzenie na emeryturę powinno być bardziej elastyczne?",
        "Czego młodsze i starsze pokolenia mogą się od siebie nauczyć?",
        "Jak dłuższe życie może zmienić edukację i karierę?",
        "Kto powinien odpowiadać za opiekę długoterminową?",
        "Jak społeczeństwo może przełamywać stereotypy związane z wiekiem?",
      ],
      JA: [
        "高齢者の自立した生活を都市はどう支援できますか？",
        "退職の時期をもっと柔軟にすべきですか？",
        "若い世代と高齢世代は互いに何を学べますか？",
        "長寿は教育や仕事をどう変えるでしょうか？",
        "長期介護の責任は誰が担うべきですか？",
        "年齢に関する固定観念をどう変えられますか？",
      ],
    },
    vocabulary: [
      ["life expectancy", "średnia długość życia", "平均寿命", "noun"],
      ["retirement", "emerytura", "退職", "noun"],
      ["long-term care", "opieka długoterminowa", "長期介護", "noun"],
      ["independent living", "samodzielne życie", "自立生活", "noun"],
      ["adapt to", "dostosować się do", "適応する", "verb"],
    ],
  },
];

export const expandedTopics: Topic[] = topicSeeds.map(createTopic);
