import type { LocalizedText, Topic } from "../domain/types";

const text = (EN: string, PL: string, JA: string): LocalizedText => ({
  EN,
  PL,
  JA,
});

const vocabulary = (
  entries: Array<[string, string, string, string]>,
): Topic["vocabulary"] => ({
  EN: entries.map(([word, translation, , part]) => ({
    word,
    translation,
    part,
  })),
  PL: entries.map(([word, translation, , part]) => ({
    word: translation,
    translation: word,
    part,
  })),
  JA: entries.map(([word, , translation, part]) => ({
    word: translation,
    translation: word,
    part,
  })),
});

const localizedVocabulary = vocabulary;

export const moreTopics: Topic[] = [
  {
    id: "sustainable-shopping",
    level: "A2",
    languages: ["EN", "PL"],
    category: "Environment",
    artIndex: 0,
    atlas: 2,
    title: text("Sustainable Shopping", "Odpowiedzialne zakupy", "環境にやさしい買い物"),
    description: text(
      "Compare everyday choices that reduce waste while shopping.",
      "Porównaj codzienne wybory, które ograniczają odpady podczas zakupów.",
      "買い物でごみを減らすための日常的な選択を比べましょう。",
    ),
    mainPrompt: text(
      "What can people change to make their shopping more sustainable?",
      "Co ludzie mogą zmienić, aby robić zakupy w bardziej odpowiedzialny sposób?",
      "より環境にやさしい買い物をするために、何を変えられますか？",
    ),
    followUps: {
      EN: [
        "Do you bring your own shopping bag?",
        "Which products do you try to buy locally?",
        "Is sustainable shopping usually more expensive?",
        "What packaging would you like stores to stop using?",
        "Would you buy more second-hand products?",
      ],
      PL: [
        "Czy zabierasz własną torbę na zakupy?",
        "Które produkty starasz się kupować lokalnie?",
        "Czy odpowiedzialne zakupy są zwykle droższe?",
        "Z jakich opakowań sklepy powinny zrezygnować?",
        "Czy kupowałbyś więcej rzeczy używanych?",
      ],
      JA: [
        "買い物袋を持参しますか？",
        "どんな商品を地元で買うようにしていますか？",
        "環境にやさしい買い物は高いことが多いですか？",
        "店にどんな包装をやめてほしいですか？",
        "中古品をもっと買いたいですか？",
      ],
    },
    vocabulary: localizedVocabulary([
      ["reusable", "wielokrotnego użytku", "再利用できる", "adjective"],
      ["packaging", "opakowanie", "包装", "noun"],
      ["local product", "produkt lokalny", "地元の商品", "noun"],
      ["second-hand", "używany", "中古の", "adjective"],
      ["reduce waste", "ograniczać odpady", "ごみを減らす", "verb"],
    ]),
  },
  {
    id: "first-job",
    level: "B1",
    languages: ["EN", "PL"],
    category: "Work & Career",
    artIndex: 1,
    atlas: 2,
    title: text("My First Job", "Moja pierwsza praca", "初めての仕事"),
    description: text(
      "Share what a first job can teach beyond the work itself.",
      "Porozmawiaj o tym, czego pierwsza praca uczy poza samymi obowiązkami.",
      "初めての仕事から、業務以外に何を学べるか話しましょう。",
    ),
    mainPrompt: text(
      "What makes a first job a valuable experience?",
      "Co sprawia, że pierwsza praca jest wartościowym doświadczeniem?",
      "初めての仕事を価値ある経験にするものは何ですか？",
    ),
    followUps: {
      EN: [
        "What was or would be your ideal first job?",
        "Which skill matters most for a new employee?",
        "How should a manager support a beginner?",
        "What mistake is normal in a first job?",
        "Should teenagers work part-time?",
      ],
      PL: [
        "Jaka była lub byłaby Twoja idealna pierwsza praca?",
        "Która umiejętność jest najważniejsza dla nowego pracownika?",
        "Jak przełożony powinien wspierać początkującą osobę?",
        "Jaki błąd jest normalny w pierwszej pracy?",
        "Czy nastolatki powinny pracować w niepełnym wymiarze?",
      ],
      JA: [
        "理想の初めての仕事は何ですか？",
        "新人に一番大切なスキルは何ですか？",
        "上司は初心者をどう支えるべきですか？",
        "初めての仕事ではどんな失敗が普通ですか？",
        "10代はアルバイトをするべきですか？",
      ],
    },
    vocabulary: localizedVocabulary([
      ["employee", "pracownik", "従業員", "noun"],
      ["responsibility", "odpowiedzialność", "責任", "noun"],
      ["training", "szkolenie", "研修", "noun"],
      ["shift", "zmiana", "シフト", "noun"],
      ["gain experience", "zdobywać doświadczenie", "経験を積む", "verb"],
    ]),
  },
  {
    id: "online-friendships",
    level: "B2",
    languages: ["EN", "PL"],
    category: "People & Relationships",
    artIndex: 2,
    atlas: 2,
    title: text("Friendship Online", "Przyjaźń w internecie", "オンラインの友情"),
    description: text(
      "Discuss trust, closeness, and communication in online friendships.",
      "Porozmawiaj o zaufaniu, bliskości i komunikacji w internetowych przyjaźniach.",
      "オンラインの友情における信頼、親しさ、コミュニケーションを考えましょう。",
    ),
    mainPrompt: text(
      "Can an online friendship be as meaningful as an offline friendship?",
      "Czy przyjaźń online może być równie wartościowa jak przyjaźń offline?",
      "オンラインの友情は、実際に会う友情と同じくらい深くなれますか？",
    ),
    followUps: {
      EN: [
        "What helps people build trust online?",
        "Which misunderstandings happen more easily in messages?",
        "Should online friends try to meet in person?",
        "How do time zones affect a friendship?",
        "What makes an online community feel safe?",
      ],
      PL: [
        "Co pomaga budować zaufanie w internecie?",
        "Jakie nieporozumienia łatwiej powstają w wiadomościach?",
        "Czy znajomi z internetu powinni spotkać się osobiście?",
        "Jak strefy czasowe wpływają na przyjaźń?",
        "Co sprawia, że społeczność internetowa jest bezpieczna?",
      ],
      JA: [
        "オンラインで信頼を築くには何が必要ですか？",
        "メッセージではどんな誤解が起こりやすいですか？",
        "オンラインの友達とは実際に会うべきですか？",
        "時差は友情にどう影響しますか？",
        "安全なオンラインコミュニティには何が必要ですか？",
      ],
    },
    vocabulary: localizedVocabulary([
      ["trust", "zaufanie", "信頼", "noun"],
      ["misunderstanding", "nieporozumienie", "誤解", "noun"],
      ["keep in touch", "utrzymywać kontakt", "連絡を取り合う", "verb"],
      ["community", "społeczność", "コミュニティ", "noun"],
      ["meaningful", "wartościowy", "意味のある", "adjective"],
    ]),
  },
  {
    id: "city-or-country",
    level: "A2",
    languages: ["EN", "PL"],
    category: "Daily Life",
    artIndex: 3,
    atlas: 2,
    title: text("City or Countryside", "Miasto czy wieś", "都会と田舎"),
    description: text(
      "Compare the pace, convenience, and atmosphere of two ways of living.",
      "Porównaj tempo, wygodę i atmosferę dwóch sposobów życia.",
      "都会と田舎の生活の速さ、便利さ、雰囲気を比べましょう。",
    ),
    mainPrompt: text(
      "Would you rather live in a large city or in the countryside?",
      "Wolałbyś mieszkać w dużym mieście czy na wsi?",
      "大都市と田舎では、どちらに住みたいですか？",
    ),
    followUps: {
      EN: [
        "Where is it easier to meet people?",
        "Which place is better for families?",
        "What do you miss when you leave a city?",
        "What do you miss when you leave the countryside?",
        "Could you live without a car?",
      ],
      PL: [
        "Gdzie łatwiej poznawać ludzi?",
        "Które miejsce jest lepsze dla rodzin?",
        "Czego brakuje Ci poza miastem?",
        "Czego brakuje Ci poza wsią?",
        "Czy mógłbyś żyć bez samochodu?",
      ],
      JA: [
        "人と出会いやすいのはどちらですか？",
        "家族にとって良いのはどちらですか？",
        "都会を離れると何が恋しくなりますか？",
        "田舎を離れると何が恋しくなりますか？",
        "車なしで生活できますか？",
      ],
    },
    vocabulary: localizedVocabulary([
      ["crowded", "zatłoczony", "混雑した", "adjective"],
      ["peaceful", "spokojny", "静かな", "adjective"],
      ["convenient", "wygodny", "便利な", "adjective"],
      ["neighborhood", "okolica", "近所", "noun"],
      ["pace of life", "tempo życia", "生活のペース", "noun"],
    ]),
  },
  {
    id: "language-learning-habits",
    level: "A2",
    languages: ["EN", "JA"],
    category: "Education",
    artIndex: 4,
    atlas: 2,
    title: text("Language Learning Habits", "Nawyki w nauce języków", "語学学習の習慣"),
    description: text(
      "Compare simple routines that make language practice easier to continue.",
      "Porównaj proste nawyki, które pomagają regularnie uczyć się języka.",
      "語学学習を続けやすくする簡単な習慣を比べましょう。",
    ),
    mainPrompt: text(
      "Which small habit helps you learn a language consistently?",
      "Który mały nawyk pomaga Ci regularnie uczyć się języka?",
      "語学学習を続けるために役立つ小さな習慣は何ですか？",
    ),
    followUps: {
      EN: [
        "When is the best time for you to study?",
        "How do you remember new words?",
        "Do you learn more from listening or reading?",
        "How often do you practice speaking?",
        "What makes you lose motivation?",
      ],
      PL: [
        "Kiedy najlepiej Ci się uczy?",
        "Jak zapamiętujesz nowe słowa?",
        "Więcej uczysz się przez słuchanie czy czytanie?",
        "Jak często ćwiczysz mówienie?",
        "Co sprawia, że tracisz motywację?",
      ],
      JA: [
        "いつ勉強するのが一番良いですか？",
        "新しい単語をどう覚えますか？",
        "聞くことと読むことのどちらから多く学びますか？",
        "どのくらい会話練習をしますか？",
        "どんな時にやる気をなくしますか？",
      ],
    },
    vocabulary: localizedVocabulary([
      ["practice", "ćwiczyć", "練習する", "verb"],
      ["review", "powtarzać", "復習する", "verb"],
      ["fluency", "płynność", "流暢さ", "noun"],
      ["motivation", "motywacja", "やる気", "noun"],
      ["consistently", "regularnie", "継続的に", "adverb"],
    ]),
  },
  {
    id: "public-transport",
    level: "B1",
    languages: ["EN", "JA"],
    category: "Travel & Culture",
    artIndex: 5,
    atlas: 2,
    title: text("Getting Around by Public Transport", "Podróżowanie komunikacją miejską", "公共交通での移動"),
    description: text(
      "Compare trains, buses, convenience, and travel etiquette.",
      "Porównaj pociągi, autobusy, wygodę i zasady podróżowania.",
      "電車やバス、便利さ、乗車マナーについて話しましょう。",
    ),
    mainPrompt: text(
      "What makes public transport easy and pleasant to use?",
      "Co sprawia, że komunikacja miejska jest łatwa i przyjemna w użyciu?",
      "公共交通を使いやすく快適にするものは何ですか？",
    ),
    followUps: {
      EN: [
        "Which transport system impressed you most?",
        "What should passengers avoid doing?",
        "How important is punctuality?",
        "Should public transport be free?",
        "What information helps visitors most?",
      ],
      PL: [
        "Który system transportu zrobił na Tobie największe wrażenie?",
        "Czego pasażerowie nie powinni robić?",
        "Jak ważna jest punktualność?",
        "Czy komunikacja miejska powinna być bezpłatna?",
        "Jakie informacje najbardziej pomagają turystom?",
      ],
      JA: [
        "最も印象に残った交通システムは何ですか？",
        "乗客は何を避けるべきですか？",
        "時間どおりに来ることはどのくらい重要ですか？",
        "公共交通は無料にするべきですか？",
        "旅行者にはどんな情報が一番役立ちますか？",
      ],
    },
    vocabulary: localizedVocabulary([
      ["platform", "peron", "ホーム", "noun"],
      ["fare", "opłata", "運賃", "noun"],
      ["transfer", "przesiadka", "乗り換え", "noun"],
      ["punctual", "punktualny", "時間どおりの", "adjective"],
      ["give up a seat", "ustąpić miejsca", "席を譲る", "verb"],
    ]),
  },
  {
    id: "creativity-and-technology",
    level: "B2",
    languages: ["EN", "JA"],
    category: "Technology",
    artIndex: 6,
    atlas: 2,
    title: text("Creativity and Technology", "Kreatywność i technologia", "創造性とテクノロジー"),
    description: text(
      "Explore how digital tools change the way people create and share ideas.",
      "Porozmawiaj o tym, jak narzędzia cyfrowe zmieniają tworzenie i dzielenie się pomysłami.",
      "デジタルツールが創作やアイデア共有をどう変えるか考えましょう。",
    ),
    mainPrompt: text(
      "Does technology make people more creative or more dependent on tools?",
      "Czy technologia zwiększa kreatywność, czy uzależnia od narzędzi?",
      "テクノロジーは人をより創造的にしますか、それとも道具に依存させますか？",
    ),
    followUps: {
      EN: [
        "Which creative tool has changed your work?",
        "Can AI-generated work be original?",
        "Do limitations help creativity?",
        "How should creators credit digital tools?",
        "What creative skill will remain uniquely human?",
      ],
      PL: [
        "Które narzędzie kreatywne zmieniło Twoją pracę?",
        "Czy praca generowana przez AI może być oryginalna?",
        "Czy ograniczenia pomagają kreatywności?",
        "Jak twórcy powinni informować o użyciu narzędzi cyfrowych?",
        "Która umiejętność kreatywna pozostanie wyjątkowo ludzka?",
      ],
      JA: [
        "どんな創作ツールが仕事を変えましたか？",
        "AIが作った作品はオリジナルと言えますか？",
        "制限は創造性を高めますか？",
        "制作者はデジタルツールの使用をどう示すべきですか？",
        "人間だけに残る創造的な能力は何ですか？",
      ],
    },
    vocabulary: localizedVocabulary([
      ["original", "oryginalny", "独創的な", "adjective"],
      ["creative process", "proces twórczy", "創作過程", "noun"],
      ["limitation", "ograniczenie", "制限", "noun"],
      ["inspiration", "inspiracja", "ひらめき", "noun"],
      ["give credit", "wskazać autorstwo", "クレジットを示す", "verb"],
    ]),
  },
  {
    id: "hosting-guests",
    level: "A1",
    languages: ["EN", "JA"],
    category: "Daily Life",
    artIndex: 7,
    atlas: 2,
    title: text("Welcoming Guests", "Przyjmowanie gości", "お客さんを迎える"),
    description: text(
      "Practice simple language for welcoming someone into your home.",
      "Przećwicz proste zwroty używane podczas przyjmowania kogoś w domu.",
      "家にお客さんを迎える時の簡単な表現を練習しましょう。",
    ),
    mainPrompt: text(
      "How do you make a guest feel welcome in your home?",
      "Jak sprawiasz, że gość czuje się mile widziany w Twoim domu?",
      "家でお客さんを歓迎するために何をしますか？",
    ),
    followUps: {
      EN: [
        "What drink do you offer first?",
        "Do guests take off their shoes?",
        "What food is easy to share?",
        "Where can a guest put their things?",
        "What do you say when a guest leaves?",
      ],
      PL: [
        "Jaki napój proponujesz najpierw?",
        "Czy goście zdejmują buty?",
        "Jakim jedzeniem łatwo się dzielić?",
        "Gdzie gość może położyć swoje rzeczy?",
        "Co mówisz, gdy gość wychodzi?",
      ],
      JA: [
        "最初にどんな飲み物を出しますか？",
        "お客さんは靴を脱ぎますか？",
        "一緒に食べやすい料理は何ですか？",
        "お客さんは荷物をどこに置けますか？",
        "お客さんが帰る時に何と言いますか？",
      ],
    },
    vocabulary: localizedVocabulary([
      ["guest", "gość", "お客さん", "noun"],
      ["welcome", "witać", "歓迎する", "verb"],
      ["make yourself at home", "czuj się jak u siebie", "くつろいでください", "phrase"],
      ["offer", "proponować", "勧める", "verb"],
      ["visit", "wizyta", "訪問", "noun"],
    ]),
  },
  {
    id: "seasonal-weather",
    level: "A1",
    languages: ["PL", "JA"],
    category: "Daily Life",
    artIndex: 8,
    atlas: 2,
    title: text("Weather Through the Seasons", "Pogoda w różnych porach roku", "季節の天気"),
    description: text(
      "Use simple words to compare favorite seasons and weather.",
      "Użyj prostych słów, aby porównać ulubione pory roku i pogodę.",
      "好きな季節や天気を簡単な言葉で比べましょう。",
    ),
    mainPrompt: text(
      "Which season do you like best, and what is the weather like?",
      "Którą porę roku lubisz najbardziej i jaka jest wtedy pogoda?",
      "どの季節が一番好きですか？その季節の天気はどうですか？",
    ),
    followUps: {
      EN: [
        "What do you wear in winter?",
        "What do you enjoy doing in spring?",
        "Is summer too hot where you live?",
        "What colors do you see in autumn?",
        "Do you like rainy days?",
      ],
      PL: [
        "Co nosisz zimą?",
        "Co lubisz robić wiosną?",
        "Czy lato jest za gorące w Twoim miejscu zamieszkania?",
        "Jakie kolory widzisz jesienią?",
        "Czy lubisz deszczowe dni?",
      ],
      JA: [
        "冬は何を着ますか？",
        "春は何をするのが好きですか？",
        "住んでいる所の夏は暑すぎますか？",
        "秋にはどんな色が見えますか？",
        "雨の日が好きですか？",
      ],
    },
    vocabulary: localizedVocabulary([
      ["season", "pora roku", "季節", "noun"],
      ["sunny", "słoneczny", "晴れた", "adjective"],
      ["cloudy", "pochmurny", "曇りの", "adjective"],
      ["snow", "śnieg", "雪", "noun"],
      ["warm", "ciepły", "暖かい", "adjective"],
    ]),
  },
  {
    id: "work-culture",
    level: "B2",
    languages: ["PL", "JA"],
    category: "Work & Career",
    artIndex: 9,
    atlas: 2,
    title: text("Work Culture Across Countries", "Kultura pracy w różnych krajach", "国による働き方の違い"),
    description: text(
      "Compare communication, hierarchy, meetings, and expectations at work.",
      "Porównaj komunikację, hierarchię, spotkania i oczekiwania w pracy.",
      "職場でのコミュニケーション、上下関係、会議、期待を比べましょう。",
    ),
    mainPrompt: text(
      "Which parts of work culture are most difficult to adapt to in another country?",
      "Do których elementów kultury pracy najtrudniej przyzwyczaić się w innym kraju?",
      "外国で働く時、どんな職場文化に慣れるのが一番難しいですか？",
    ),
    followUps: {
      EN: [
        "How directly should colleagues disagree?",
        "What makes a meeting productive?",
        "How important is hierarchy?",
        "Should employees socialize after work?",
        "How can international teams avoid misunderstandings?",
      ],
      PL: [
        "Jak bezpośrednio współpracownicy powinni wyrażać sprzeciw?",
        "Co sprawia, że spotkanie jest produktywne?",
        "Jak ważna jest hierarchia?",
        "Czy pracownicy powinni spotykać się po pracy?",
        "Jak międzynarodowe zespoły mogą unikać nieporozumień?",
      ],
      JA: [
        "同僚と意見が違う時、どのくらい直接伝えるべきですか？",
        "生産的な会議には何が必要ですか？",
        "上下関係はどのくらい重要ですか？",
        "仕事の後に同僚と交流するべきですか？",
        "国際チームはどうすれば誤解を避けられますか？",
      ],
    },
    vocabulary: localizedVocabulary([
      ["hierarchy", "hierarchia", "上下関係", "noun"],
      ["expectation", "oczekiwanie", "期待", "noun"],
      ["direct communication", "bezpośrednia komunikacja", "直接的な伝え方", "noun"],
      ["consensus", "konsensus", "合意", "noun"],
      ["adapt", "przystosować się", "適応する", "verb"],
    ]),
  },
  {
    id: "family-traditions",
    level: "B1",
    languages: ["PL", "JA"],
    category: "People & Relationships",
    artIndex: 10,
    atlas: 2,
    title: text("Traditions at Home", "Tradycje w domu", "家庭の伝統"),
    description: text(
      "Share family customs that create memories and a sense of belonging.",
      "Opowiedz o rodzinnych zwyczajach, które tworzą wspomnienia i poczucie bliskości.",
      "思い出や家族のつながりを作る習慣について話しましょう。",
    ),
    mainPrompt: text(
      "Which family tradition would you like to continue in the future?",
      "Którą rodzinną tradycję chciałbyś kontynuować w przyszłości?",
      "これからも続けたい家族の伝統は何ですか？",
    ),
    followUps: {
      EN: [
        "Who usually organizes the tradition?",
        "Has the tradition changed over time?",
        "Which food or object is connected to it?",
        "Can new traditions be as meaningful as old ones?",
        "How do families preserve memories?",
      ],
      PL: [
        "Kto zwykle organizuje tę tradycję?",
        "Czy tradycja zmieniła się z czasem?",
        "Jakie jedzenie lub przedmiot jest z nią związany?",
        "Czy nowe tradycje mogą być równie ważne jak stare?",
        "Jak rodziny zachowują wspomnienia?",
      ],
      JA: [
        "その伝統は誰が準備しますか？",
        "その伝統は時代とともに変わりましたか？",
        "どんな食べ物や物が関係していますか？",
        "新しい伝統も古い伝統と同じくらい大切になれますか？",
        "家族はどうやって思い出を残しますか？",
      ],
    },
    vocabulary: localizedVocabulary([
      ["custom", "zwyczaj", "習慣", "noun"],
      ["generation", "pokolenie", "世代", "noun"],
      ["memory", "wspomnienie", "思い出", "noun"],
      ["belonging", "poczucie przynależności", "帰属意識", "noun"],
      ["pass on", "przekazywać", "受け継ぐ", "verb"],
    ]),
  },
  {
    id: "future-of-education",
    level: "C1",
    languages: ["PL", "JA"],
    category: "Education",
    artIndex: 11,
    atlas: 2,
    title: text("The Future of Education", "Przyszłość edukacji", "教育の未来"),
    description: text(
      "Debate how schools should balance technology, knowledge, and human development.",
      "Porozmawiaj o tym, jak szkoły powinny łączyć technologię, wiedzę i rozwój człowieka.",
      "学校がテクノロジー、知識、人間的成長をどう両立すべきか議論しましょう。",
    ),
    mainPrompt: text(
      "What should education prepare people for in a rapidly changing world?",
      "Do czego edukacja powinna przygotowywać ludzi w szybko zmieniającym się świecie?",
      "急速に変化する世界で、教育は人々を何に備えさせるべきですか？",
    ),
    followUps: {
      EN: [
        "Which knowledge should every student still learn?",
        "How should schools use artificial intelligence?",
        "Should assessment focus less on exams?",
        "What role will teachers have in twenty years?",
        "How can education remain fair and accessible?",
      ],
      PL: [
        "Jaką wiedzę każdy uczeń nadal powinien zdobywać?",
        "Jak szkoły powinny korzystać ze sztucznej inteligencji?",
        "Czy ocenianie powinno mniej opierać się na egzaminach?",
        "Jaką rolę będą mieli nauczyciele za dwadzieścia lat?",
        "Jak edukacja może pozostać sprawiedliwa i dostępna?",
      ],
      JA: [
        "すべての生徒が学ぶべき知識は何ですか？",
        "学校はAIをどう使うべきですか？",
        "評価は試験を重視しすぎない方が良いですか？",
        "20年後、先生はどんな役割を持つでしょうか？",
        "公平で利用しやすい教育をどう実現できますか？",
      ],
    },
    vocabulary: localizedVocabulary([
      ["assessment", "ocenianie", "評価", "noun"],
      ["critical thinking", "krytyczne myślenie", "批判的思考", "noun"],
      ["accessible", "dostępny", "利用しやすい", "adjective"],
      ["curriculum", "program nauczania", "カリキュラム", "noun"],
      ["prepare for", "przygotować do", "備える", "verb"],
    ]),
  },
];
